### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException when using decompressFromUTF16

### ISSUE THREAD

**Issue by dasmikko** [rufushuang/lz-string4java#5]
I'm getting this error when decompressing strings longer than 44 characters. 

I using the method: `decompressFromUTF16`

`java.lang.ArrayIndexOutOfBoundsException: length=44; index=44`

**Comment by rufushuang** [comment]
Can your string with 44 character, pass the LZStringInRhino144.java & LZStringInRhino.java?

```
input = "hello1hello2hello3hello4hello5hello6hello7hello8hello9helloAhelloBhelloChelloDhelloEhelloF";
```

my original test string is 90 characters, more than 44 characters.

So, what's your string, and what version of lz-string you use at webpage-side?

**Caution:**

Original LZString is not all version compatible.

From version 1.3.3 to version 1.4.4, there are some incompatible changes in compressToBase64/decompressFromBase64. Same as EncodedURIComponent. Use different will result in failure.

So just keep appropriate/same version on your web page javascript side and server java side.

IF YOU USE LZ-String VERSION WHICH BACKWARDS OF 1.4.4 and have problem with Base64/URIComponent, go to my release part and get the 1.3.3 release to have a try.

**Comment by dasmikko** [comment]
It's this string: 夨൉格ⓚ戃᧰ఀᎢ孲ᵮ潛㲹狲ʫ䙘䆶坶ح⴬䬠⇸秷溚瀻䔠剞⇃浦Ѯฃ᭛䠠

When I use 1.3.3, i get this error, when using this string: 
`&崨ޏᒤᣄ᤹岅滻㧆校࠰ɰၡ‱獪ၶ൩ᚅ㋐䲅ਾ彙̣䨡耕䨫㜾⑝ⷋԵଡϻ䅘䳸╢⢂ᎁ䈠`
`java.lang.ArrayIndexOutOfBoundsException: length=35; index=35`

**Comment by rufushuang** [comment]
With your string, I pass the test in LZStringInRhino144.java & LZStringInRhino.java. So most likely this in not a issue cause by my project.

And your string is full of unprintable character, i wonder whether github will show it exactly what you wrote.

The method to determine if there is some mistake in my project, just run the string in LZStringInRhino144.java & LZStringInRhino.java, replace the test string in the main function.

If it fails in print different string with your test string, upload a text file, so I can test in raw string, prevent  github shows something weird.

further, maybe you can see:
https://github.com/rufushuang/lz-string4java/issues/1
https://github.com/rufushuang/lz-string4java/issues/4

**Comment by rufushuang** [comment]
If there is no further information to determine whether this is really a problem, i will close this issue in a week.
